### ISSUE TITLE
Error "'PrettyLine' is not convertible to '[PrettyLine]'" caused by struct comparison on Swift 4.0.x

### ISSUE THREAD

**Issue by imaizume** [Kuniwak/MirrorDiffKit#36]
(English content was translated by @kuniwak)

## 🔴 Abstract
I got the following errors when comparing any structs: 

<img width="532" alt="2018-05-31 14 49 59" src="https://user-images.githubusercontent.com/16273903/40763960-e8460dde-64e1-11e8-9d1b-ec28e77bc349.png">

> Error:(203, 53) 'PrettyLine' is not convertible to '[PrettyLine]'
> Error:(222, 53) 'PrettyLine' is not convertible to '[PrettyLine]'
> Error:(242, 57) 'PrettyLine' is not convertible to '[PrettyLine]'

And the line 203 is the following:

https://github.com/Kuniwak/MirrorDiffKit/blob/master/Sources/Diffable+PrettyPrintable.swift#L203

```swift
return [head] + childLines(by: entries) + [tail]
```

So I put `childLines(by:)` as a temporary variable like following, then the compilation is succeeded:

```swift
let lines = childLines(by: entries)
return [head] + lines + [tail]
```

Is it a type inference problem?

## 💻 Environment

- XCode 9.2 (9C40b)
- Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)

---

## 🔴 概要

MirrorDiffKitをimportしてstructのdiffをassertしようとしたところ、コンパイル時点で以下のエラーが出ました

<img width="532" alt="2018-05-31 14 49 59" src="https://user-images.githubusercontent.com/16273903/40763960-e8460dde-64e1-11e8-9d1b-ec28e77bc349.png">

> Error:(203, 53) 'PrettyLine' is not convertible to '[PrettyLine]'
> Error:(222, 53) 'PrettyLine' is not convertible to '[PrettyLine]'
> Error:(242, 57) 'PrettyLine' is not convertible to '[PrettyLine]'

203行目は以下のようになっていましたが

https://github.com/Kuniwak/MirrorDiffKit/blob/master/Sources/Diffable+PrettyPrintable.swift#L203

```swift
return [head] + childLines(by: entries) + [tail]
```

試しに `childLines(by:)` を一時変数に置いたところコンパイルは通りました。

```swift
let lines = childLines(by: entries)
return [head] + lines + [tail]
```

型推論がうまくいっていないのでしょうか ❓ 

## 💻 環境

- XCode 9.2 (9C40b)
- Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)

**Comment by Kuniwak** [comment]
I could reproduce the problem on Swift 4.0.x by the following:

```
$ DEVELOPER_DIR="/Applications/Xcode-9.1.app" xcrun swift test
Compile Swift Module 'MirrorDiffKit' (30 sources)
/Users/kuniwak/Development/MirrorDiffKit/Sources/Diffable+PrettyPrintable.swift:203:53: error: 'PrettyLine' is not convertible to '[PrettyLine]'
            return [head] + childLines(by: entries) + [tail]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/kuniwak/Development/MirrorDiffKit/Sources/Diffable+PrettyPrintable.swift:222:53: error: 'PrettyLine' is not convertible to '[PrettyLine]'
            return [head] + childLines(by: entries) + [tail]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/kuniwak/Development/MirrorDiffKit/Sources/Diffable+PrettyPrintable.swift:242:57: error: 'PrettyLine' is not convertible to '[PrettyLine]'
                return [head] + childLines(by: entries) + [tail]
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
error: terminated(1): /Applications/Xcode-9.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/kuniwak/Development/MirrorDiffKit/.build/debug.yaml test
```

But this problem couldn't reproduce on Swift 4.1, so I think it is a type inference bug.

**Comment by Kuniwak** [comment]
I started to work on #37

**Comment by Kuniwak** [comment]
I shipped the fix on [v3.0.1](https://github.com/Kuniwak/MirrorDiffKit/releases/tag/3.0.1). Please try it.

**Comment by Kuniwak** [comment]
@imaizume Is your problem fixed?

**Comment by imaizume** [comment]
@Kuniwak Thank you, LGTM!
